export const COLLEGES = [
  "Government Arts and Science College, Sivakasi",
  "Government Arts and Science College, Sattur",
  "Government Arts and Science College, Aruppukottai",
  "Government Arts and Science College, Srivilliputhur",
  "Government Arts and Science College, Tiruchuli",
  "Ayya Nadar Janaki Ammal College (Autonomous)",
  "Virudhunagar Hindu Nadars' Senthikumara Nadar College (V.H.N.S.N. College)",
  "The Standard Fireworks Rajaratnam College for Women",
  "SFR College for Women",
  "Raju's College",
  "Sri. Ramasamy Naidu Memorial College, Sattur",
  "A.K.D. Dharmaraja Women's College",
  "Devanga Arts College",
  "Saiva Bhanu Kshatriya College (SBK College)",
  "Sri Kaliswari College",
  "Jai Sairam Arts and Science College",
  "AAA College of Arts and Science",
  "PSR Arts and Science College",
  "V.P.M.M. Arts and Science College for Women",
  "Kalasalingam Academy of Research and Education",
  "Mepco Schlenk Engineering College",
  "Sethu Institute of Technology",
  "Kamaraj College of Engineering and Technology",
  "AAA College of Engineering and Technology",
  "Sri Vidya College of Engineering and Technology",
  "PSR Engineering College",
  "PSR Rengasamy College of Engineering for Women",
  "Ramco Institute of Technology",
  "SBM College of Engineering and Technology",
  "Kalasalingam Institute of Technology",
  "Virudhunagar S. Vellaichamy Nadar Polytechnic College",
  "Arasan Ganesan Polytechnic College",
  "Ayya Nadar Janaki Ammal Women's Polytechnic College",
  "P.A.C. Ramasamy Raja's Polytechnic College",
  "N.A. Manjammal Polytechnic College",
  "PSR Polytechnic College",
  "Arulmigu Kalasalingam Polytechnic College",
  "Ramu Seetha Polytechnic College",
  "Sri Sowdambika Polytechnic College",
  "Sri Vatsa Polytechnic College",
  "Sri Boghar Polytechnic College",
  "SMS Polytechnic College",
  "Sivakasi Institute of Printing Technology",
  "Annai Madha Polytechnic College",
  "PSR College of Education",
  "PSR Rengasamy College of Education",
  "Kalasalingam College of Education",
  "Sivakasi College of Education",
  "Kalasalingam College of Nursing",
  "Ramco College of Nursing",
  "Sivakasi College of Nursing",
  "Kalasalingam College of Pharmacy",
  "Kalasalingam Institute of Physiotherapy",
  "Ramco Institute of Allied Health Sciences",
  "Kalasalingam Business School",
  "Ramco Institute of Management Studies",
  "PSR Institute of Management Studies",
  "Sri Kaliswari Institute of Management",
  "AAA School of Management",
  "Kalasalingam School of Computing",
  "Kalasalingam School of Architecture",
  "Kalasalingam School of Agricultural Sciences",
  "Kalasalingam School of Advanced Sciences",
  "Kalasalingam School of Bio and Chemical Engineering",
  "Kalasalingam School of Mechanical Engineering",
  "Kalasalingam School of Civil Engineering",
  "Kalasalingam School of Electrical and Electronics Engineering",
  "Kalasalingam School of Electronics and Communication Engineering",
  "Kalasalingam School of Liberal Arts and Education",
  "Others"
];
