export const COLLEGES = [
  "Cardamom Planters' Association (CPA) College,Bodinayakanur",
  "Hajee Karutha Rowther Howdia College,Uthamapalayam",
  "Government Arts and Science College,Andipatti",
  "Government Arts and Science College,Kottur",
  "Government Arts and Science College,Veerapandi",
  "Jayaraj Annapackiam College for Women,Periyakulam",
  "Nadar Saraswathi College of Arts and Science,Theni",
  "Theni College of Arts and Science,Veerapandi",
  "Mary Matha College of Arts and Science,Periyakulam",
  "Mother Theresa Arts and Science College,T. Sindalacheri",
  "Jeyaraj Chelladurai College of Arts and Science,Theni",
  "Sri Adi Chunchanagiri Women's College,Cumbum",
  "Thiravium College of Arts & Science for Women,Theni",
  "Government College of Engineering,Theni",
  "Bharath Niketan Engineering College,Andipatti",
  "Theni Kammavar Sangam College of Technology,Theni",
  "Odaiyappa College of Engineering and Technology,Theni",
  "Government Polytechnic College,Andipatti",
  "Government Polytechnic College,Kottur",
  "Bharath Niketan Polytechnic College,Andipatti",
  "Devangar Polytechnic College,Theni",
  "Kala Pandian Polytechnic College,Theni",
  "Thangam Muthu Polytechnic College,Periyakulam",
  "Theni Kammavar Sangam Polytechnic College,Theni",
  "Theni Government Medical College,Theni",
  "Theni Government College of Nursing,Theni",
  "Nadar Saraswathi College of Nursing,Theni",
  "Mary Matha College of Nursing,Periyakulam",
  "Nadar Saraswathi College of Pharmacy,Theni",
  "College of Pharmacy, Theni Government Medical College,Theni",
  "Horticultural College and Research Institute,Periyakulam",
  "College of Agricultural Technology,Theni",
  "District Institute of Education and Training (DIET),Uthamapalayam",
  "Theni Institute of Cooperative Management,Andipatti",
  "Madurai Kamaraj University Evening College,Periyakulam",
  "Government Industrial Training Institute (ITI),Theni",
  "Government Industrial Training Institute (ITI),Periyakulam",
  "Government Industrial Training Institute (ITI),Bodinayakanur",
  "Government Industrial Training Institute (ITI),Andipatti",
  "Government Industrial Training Institute (ITI),Cumbum",
  "Government Industrial Training Institute (ITI),Uthamapalayam",
  "Theni Institute of Management Studies,Theni",
  "Nadar Saraswathi MBA Department,Theni",
  "Government College of Engineering MBA Department,Theni",
  "Bharath Niketan MBA Department,Andipatti",
  "Theni College of Arts and Science MBA Department,Veerapandi",
  "Mother Theresa Teacher Training Institute,T. Sindalacheri",
  "Nadar Saraswathi College of Education,Theni",
  "Mary Matha College of Education,Periyakulam"
];
