import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generateStudentReportPDF = (reportData) => {
  const doc = new jsPDF();
  const { student, assessmentSummary, topics, weakTopics } = reportData;

  // Colors
  const primaryColor = [31, 41, 55]; // Slate 800
  const secondaryColor = [71, 85, 105]; // Slate 600
  const accentColor = [37, 99, 235]; // Blue 600
  const lightBg = [248, 250, 252]; // Slate 50
  
  const getPerformanceColor = (perf) => {
    switch(perf) {
      case 'Excellent': return [16, 185, 129]; // Emerald
      case 'Strong': return [52, 211, 153];
      case 'Average': return [245, 158, 11]; // Amber
      case 'Weak': return [249, 115, 22]; // Orange
      case 'Needs Improvement': return [239, 68, 68]; // Red
      default: return [156, 163, 175];
    }
  };

  // Header
  doc.setFontSize(22);
  doc.setTextColor(...primaryColor);
  doc.setFont('helvetica', 'bold');
  doc.text('Employment Connect', 14, 20);
  
  doc.setFontSize(14);
  doc.setTextColor(...accentColor);
  doc.text('Student Weak Topic Analysis Report', 14, 28);
  
  doc.setDrawColor(226, 232, 240);
  doc.line(14, 32, 196, 32);

  // Student Details & Summary
  doc.setFontSize(10);
  doc.setTextColor(...secondaryColor);
  doc.setFont('helvetica', 'normal');
  
  // Left Column: Student Details
  let startY = 40;
  doc.setFont('helvetica', 'bold');
  doc.text('Student Information', 14, startY);
  doc.setFont('helvetica', 'normal');
  doc.text(`Name: ${student.name}`, 14, startY + 6);
  doc.text(`Register No: ${student.registerNumber}`, 14, startY + 12);
  doc.text(`College: ${student.college}`, 14, startY + 18);
  doc.text(`Department: ${student.department}`, 14, startY + 24);
  doc.text(`Year: ${student.year}`, 14, startY + 30);

  // Right Column: Assessment Details
  doc.setFont('helvetica', 'bold');
  doc.text('Assessment Summary', 110, startY);
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Questions: ${assessmentSummary.totalQuestions}`, 110, startY + 6);
  doc.text(`Correct Answers: ${assessmentSummary.correctAnswers}`, 110, startY + 12);
  doc.text(`Wrong Answers: ${assessmentSummary.wrongAnswers}`, 110, startY + 18);
  doc.text(`Overall Score: ${assessmentSummary.score} (${assessmentSummary.percentage}%)`, 110, startY + 24);
  doc.text(`Overall Grade: ${assessmentSummary.grade}`, 110, startY + 30);

  startY += 40;
  
  // Topic-wise Performance Table
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...primaryColor);
  doc.text('Topic-wise Performance', 14, startY);
  
  const tableData = topics.map(t => [
    t.topic,
    t.total,
    t.correct,
    t.wrong,
    `${t.percentage}%`,
    t.performance
  ]);

  doc.autoTable({
    startY: startY + 4,
    head: [['Topic', 'Total Qs', 'Correct', 'Wrong', 'Percentage', 'Performance']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: accentColor, textColor: 255 },
    styles: { fontSize: 9, cellPadding: 4 },
    willDrawCell: function(data) {
      if (data.section === 'body' && data.column.index === 5) {
        doc.setTextColor(...getPerformanceColor(data.cell.raw));
        doc.setFont('helvetica', 'bold');
      }
    }
  });

  startY = doc.lastAutoTable.finalY + 15;

  // Weak Topics Summary & Recommendations
  if (weakTopics && weakTopics.length > 0) {
    // Check page break
    if (startY > 250) {
      doc.addPage();
      startY = 20;
    }

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...primaryColor);
    doc.text('Weak Topics & AI Recommendations', 14, startY);
    
    startY += 8;
    doc.setFontSize(10);
    
    weakTopics.forEach((t) => {
      if (startY > 270) {
        doc.addPage();
        startY = 20;
      }
      
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...getPerformanceColor(t.performance));
      doc.text(`${t.topic} (${t.performance})`, 14, startY);
      
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...secondaryColor);
      const recs = `Practice Areas: ${t.recommendations.join(', ')}`;
      
      // Wrap text
      const splitText = doc.splitTextToSize(recs, 180);
      doc.text(splitText, 14, startY + 5);
      
      startY += 5 + (splitText.length * 5);
    });
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    const dateStr = `Report Generated On: ${new Date().toLocaleString()}`;
    doc.text('Generated by Employment Connect', 14, 285);
    doc.text(dateStr, 196 - doc.getTextWidth(dateStr), 285);
    doc.text(`Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
  }

  doc.save(`${student.name.replace(/\s+/g, '_')}_Skill_Gap_Report.pdf`);
};
